# Generated by Django 3.2.6 on 2021-08-18 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='EducationOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('mail', models.CharField(max_length=30, verbose_name='Адрес почты')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'education_office',
            },
        ),
        migrations.CreateModel(
            name='GeneralOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('mail', models.CharField(max_length=30, verbose_name='Адрес почты')),
                ('name', models.TextField(verbose_name='Название головного офиса ')),
            ],
            options={
                'db_table': 'office',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('last_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('startwork_date', models.DateField(null=True, verbose_name='Дата выхода на работу')),
                ('tab_num', models.IntegerField(default=0, verbose_name='Табельный номер')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='day8.department')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'workers',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('worker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='day8.worker')),
                ('grade', models.IntegerField(default=1, verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Директор',
                'verbose_name_plural': 'Директора',
                'db_table': 'directors',
            },
            bases=('day8.worker',),
        ),
        migrations.CreateModel(
            name='OrderedWorker',
            fields=[
                ('worker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='day8.worker')),
            ],
            options={
                'abstract': False,
            },
            bases=('day8.worker',),
        ),
        migrations.AddField(
            model_name='department',
            name='education_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='day8.educationoffice'),
        ),
        migrations.AddField(
            model_name='department',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='day8.generaloffice'),
        ),
    ]
