# Generated by Django 3.2.6 on 2021-08-16 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20210816_1851'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='worker',
            managers=[
            ],
        ),
    ]
